[project]
authors = ["Dan Allan <dallan@bnl.gov>"]
channels = ["conda-forge"]
description = "Daily Driver working environment"
name = "dd"
platforms = ["linux-64"]
version = "1.0.0"

[tasks]

[dependencies]
h5py = "*"
ipython = "*"
julia = "*"
jupyter = "*"
numba = "*"
numpy = "*"
pytorch = "*"
scipy = "*"
awkward = "*"
ragged = "*"

[pypi-dependencies]
bluesky = { path = "/home/dallan/Repos/bnl/bluesky", editable = true, extras = ["all"] }
databroker = { path = "/home/dallan/Repos/bnl/databroker", editable = true, extras = ["all"] }
bluesky-tiled-plugins = { path = "/home/dallan/Repos/bnl/databroker/bluesky-tiled-plugins", editable = true }
# ophyd = { path = "/home/dallan/Repos/bnl/ophyd", editable = true, extras = ["all"] }
# ophyd-async = { path = "/home/dallan/Repos/bnl/ophyd-async", editable = true, extras = ["all"] }
tiled = { path = "/home/dallan/Repos/bnl/tiled", editable = true, extras = ["all"] }

[feature.py312.dependencies]
python = "~=3.12.0"

[environments]
default = ["py312"]
